# Generated by Django 4.0.5 on 2022-07-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
    ]
