name: Djando tests and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# on:
#   schedule:
#     - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: supersecretpassword
          POSTGRES_DB: app
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python ./app/manage.py migrate
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run ./app/manage.py test core
          coverage report
#        env:
#          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
      - name: Django Testing
        run: |
          python ./app/manage.py test core